server:
  port: 8084
spring:
  datasource:
    username: root
    password: 123456a
    url: jdbc:mysql://localhost:3306/story_libraries?allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations:
      - classpath:/html/
      - classpath:/js/
      - file:D:/storyPicture/
mybatis:
  type-aliases-package: com.zxw.domain
  mapper-locations: classpath:com/zxw/mapper/*.xml
logging:
  file: root.log
  level:
    root: info
    com:
      zxw:
        dao: debug

